out_dir: results
metric_best: f1
num_workers: 4
wandb:
  use: False
  project: COCO
dataset:
  format: PyG-COCOSuperpixels
  name: edge_wt_region_boundary
  slic_compactness: 30
  task: graph  # Even if VOC is node-level task, this needs to be set as 'graph'
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: COCONode
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: COCOEdge
  edge_encoder_bn: False
posenc_RWSE:
  enable: False
  kernel:
    times_func: range(1,21)
  model: Linear
  dim_pe: 28
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 50
  eval_period: 1
  ckpt_period: 100
  eval_smoothing_metrics: True
model:
  type: gnnformer
  loss_fun: weighted_cross_entropy
gt:
  layer_type: g2lformer
  layers: 2
  n_heads: 4
  dim_hidden: 128  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.05
  attn_dropout: 0.05
  layer_norm: False
  batch_norm: True
  use_classic_gnn: True
  classic_gnn_num_layers: 8
  nw_num_layers: 1
  classic_gnn_dropout: 0.05
  residual: True
  ffn: False
  act: gelu
gnn:
  head: inductive_node
  layers_pre_mp: 0
#  layers_mp: 20
  layers_post_mp: 0
  layer_type: g2lformer
  dim_inner: 128
  # batchnorm: True
  act: gelu
  dropout: 0.05
  agg: mean
  normalize_adj: False
  ffn: False
  residual: True
#gnn:
#  head: inductive_node
#  layers_pre_mp: 0
#  layers_mp: 20
#  layers_post_mp: 1
#  layer_type: g2lformer
#  dim_inner: 52
#  # batchnorm: True
#  act: gelu
#  dropout: 0.05
#  agg: mean
#  normalize_adj: False
#  ffn: True
#  residual: True
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 300
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10