out_dir: results
metric_best: auc
wandb:
  use: False
  project: molhiv
dataset:
  format: OGB
  name: ogbg-molhiv
  task: graph
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: Atom+RWSE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,21)
  model: Linear
  dim_pe: 16
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
model:
  type: gnnformer
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: mean
gt:
  layer_type: g2lformer
  layers: 1
  n_heads: 4
  dim_hidden: 128  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.1
  attn_dropout: 0.1
  layer_norm: False
  batch_norm: True
  use_classic_gnn: True
  classic_gnn_num_layers: 2
  nw_num_layers: 1
  classic_gnn_dropout: 0.1
  residual: True
  ffn: False
  act: relu
gnn:
  head: san_graph
  layer_type: g2lformer_gcn
  layers_pre_mp: 0
  layers_post_mp: 3
#  layers_mp: 3
  dim_inner: 128
  batchnorm: True
  act: relu
  dropout: 0.1
  agg: mean
  normalize_adj: False
  ffn: False
  residual: True
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.0001
  max_epoch: 100
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5