out_dir: results
metric_best: ap
wandb:
  use: False
  project: molpcba
dataset:
  format: OGB
  name: ogbg-molpcba
  task: graph
  task_type: classification_multilabel
  transductive: False
  node_encoder: True
  node_encoder_name: Atom+RWSE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,17)
  model: Linear
  dim_pe: 20
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 512
  eval_period: 1
  ckpt_period: 100
model:
  type: gnnformer
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: mean
gt:
  layer_type: g2lformer
  layers: 5
  n_heads: 4
  dim_hidden: 128  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.0
  attn_dropout: 0.
  layer_norm: False
  batch_norm: True
  use_classic_gnn: True
  classic_gnn_num_layers: 2
  nw_num_layers: 1
  classic_gnn_dropout: 0.
  residual: True
  ffn: False
  act: relu
gnn:
  head: default  # san_graph
  layers_mp: 1
  layer_type: gatedgcn
  layers_pre_mp: 0
  layers_post_mp: 1  # Not used when `gnn.head: san_graph`
  dim_inner: 128
  batchnorm: True
  act: relu
  dropout: 0.2
  agg: mean
  normalize_adj: False
  ffn: True
  residual: True
optim:
  batch_accumulation: 1
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.0005
  max_epoch: 100
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
