out_dir: results
metric_best: ap
wandb:
  use: False
  project: peptides-func
dataset:
  format: OGB
  name: peptides-functional
  task: graph
  task_type: classification_multilabel
  transductive: False
  node_encoder: True
  node_encoder_name: Atom+RWSE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,33)
  model: Linear
  dim_pe: 28
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 16
  eval_period: 1
  ckpt_period: 100
model:
  type: gnnformer
  loss_fun: cross_entropy
  graph_pooling: mean
gt:
  layer_type: g2lformer
  layers: 1
  n_heads: 4
  dim_hidden: 256 # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.2
  attn_dropout: 0.2
  layer_norm: False
  batch_norm: True
  use_classic_gnn: True
  classic_gnn_num_layers: 4
  nw_num_layers: 1
  classic_gnn_dropout: 0.05
  residual: False
  ffn: False
  act: gelu
gnn:
  head: mlp_graph
  ffn: False
  layers_pre_mp: 0
  layers_mp: 5
  layers_post_mp: 3
  dim_inner: 256
  layer_type: g2lformer
  act: gelu
  residual: False
  dropout: 0.2
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.0005
  max_epoch: 300
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5